Feed design
zuckyskidz/team_project pull request #32
Opened 2019-07-24 20:57 UTC by aublhr99

2019-07-24 21:04 UTC, jennhe requested changes
details view does not show up

2019-07-25 06:45 UTC, baldwinchang commented on app/src/main/java/com/example/teamproject/RecAdAdapter.java
> +        return getAdapterPosition();
Is this infinite recursion?

2019-07-26 00:14 UTC, aublhr99 commented on app/src/main/java/com/example/teamproject/RecAdAdapter.java
> +        return getAdapterPosition();
fixed

2019-07-26 18:41 UTC, jennhe approved these changes
good work!!!!

2019-07-26 18:41 UTC, merged